Repository webaccess/SESTA-FMS, pull requests merged in 2020-04, with the labels that each got.

#65 Statesmodule
  backend/strapi/hooks/autoload/data.js
  backend/strapi/package-lock.json
  package-lock.json
  webapp/src/Routes.js
  webapp/src/components/Autocomplete/Autocomplete.js
  webapp/src/components/Autotext/Autotext.js
  webapp/src/components/Datatable/Datatable.js
  webapp/src/components/Datatable/Datatable.module.css
  webapp/src/components/Navigation/Breadcrumbs/Breadcrumbs.js
  webapp/src/components/Switch/Switch.js
  webapp/src/components/Switch/Switch.module.css
  webapp/src/components/Switch/Switch.test.js
  webapp/src/containers/Shgs/ShgPage.js
  webapp/src/containers/Shgs/Shgs.js
  webapp/src/containers/Shgs/config.js
  webapp/src/containers/States/StatePage.js
  webapp/src/containers/States/States.js
  webapp/src/containers/States/States.module.css
  webapp/src/containers/States/config.js
  webapp/src/containers/Villages/VillagePage.js
  webapp/src/containers/Villages/Villages.js
Labels: complete

#77 isactive filter for states and districts added in villagelist,village…
  webapp/src/containers/Shgs/Shgs.js
  webapp/src/containers/Villages/VillagePage.js
  webapp/src/containers/Villages/Villages.js
  webapp/src/containers/Vo/Vos.js
Labels: completed

#81 Pgmodule
  backend/strapi/api/tag/models/tag.settings.json
  webapp/src/containers/Pgs/PgPage.js
  webapp/src/containers/Pgs/Pgs.js
Labels: needs review

#76 added * to mandatory fields (except pg and shg) #74
  webapp/src/containers/States/StatePage.js
  webapp/src/containers/Villages/VillagePage.js
  webapp/src/containers/Vo/VoPage.js
Labels: needs review

#90 Fpopage
  backend/strapi/config/environments/development/database.json
  backend/strapi/hooks/autoload/data.js
  webapp/src/Routes.js
  webapp/src/containers/Fpos/FpoPage.js
  webapp/src/containers/Fpos/Fpos.js
  webapp/src/containers/Fpos/config.js
  webapp/src/containers/Villages/VillagePage.js
  webapp/src/containers/Villages/Villages.js
Labels: needs review
