Repository webaccess/SESTA-FMS, pull requests merged in 2020-08, with the labels that each got.

#164 Activity type module
  backend/strapi/extensions/crm-plugin/models/activity.settings.json
  backend/strapi/extensions/crm-plugin/models/activitytype.settings.json
  backend/strapi/extensions/crm-plugin/models/contact.settings.json
  backend/strapi/hooks/autoload/data.js
  webapp/src/Routes.js
  webapp/src/components/Navigation/NavigationItems/NavigationItems.js
  webapp/src/containers/Activitytypes/ActivitytypePage.js
  webapp/src/containers/Activitytypes/Activitytypes.js
  webapp/src/containers/Activitytypes/Activitytypes.module.css
  webapp/src/containers/Activitytypes/config.js
Labels: needs review

#173 Calculated Loans pending amount and fixed edit form field values
  webapp/src/containers/Loans/LoanEditEmiPage.js
  webapp/src/containers/Loans/LoanEditTask.js
  webapp/src/containers/Loans/LoanEmiPage.js
  webapp/src/containers/Loans/LoanUpdateTaskPage.js
Labels: needs review

#175 Pre-populated default emi values in EMI edit form, updated loan ends …
  webapp/src/components/Datatable/Datatable.js
  webapp/src/components/UI/Datepicker/Datepicker.js
  webapp/src/components/UI/Datepicker/Datepicker.module.css
  webapp/src/containers/Activitytypes/Activitytypes.js
  webapp/src/containers/Countries/Countries.js
  webapp/src/containers/Fpos/Fpos.js
  webapp/src/containers/Loanpurpose/Loanpurposes.js
  webapp/src/containers/Loans/LoanEditEmiPage.js
  webapp/src/containers/Loans/LoanEmiPage.js
  webapp/src/containers/Loans/LoanUpdateTaskPage.js
  webapp/src/containers/Members/Members.js
  webapp/src/containers/Pgs/Pgs.js
  webapp/src/containers/Shgs/Shgs.js
  webapp/src/containers/States/States.js
  webapp/src/containers/Villages/Villages.js
  webapp/src/containers/Vo/Vos.js
Labels: needs review

#177 Added records in Activities and Activityassignees model while updating l…
  backend/strapi/api/loan-application-installments/models/loan-application-installments.settings.json
  backend/strapi/extensions/crm-plugin/models/activity.settings.json
  backend/strapi/extensions/crm-plugin/models/activityassignee.settings.json
  backend/strapi/extensions/crm-plugin/models/activitytype.settings.json
  webapp/src/containers/Loans/LoanApprovalPage.js
  webapp/src/containers/Loans/LoanEditEmiPage.js
  webapp/src/containers/Loans/LoanEditTask.js
  webapp/src/containers/Loans/LoanUpdateTaskPage.js
Labels: needs review

#184 Fixed to populate amount due after loan approval and added outstandin…
  webapp/src/containers/Loans/LoanApprovalPage.js
  webapp/src/containers/Loans/LoanEditEmiPage.js
  webapp/src/containers/Loans/Loans.js
Labels: needs review

#185 Loan emi view
  backend/strapi/hooks/autoload/data.js
  webapp/src/Routes.js
  webapp/src/components/Datatable/Datatable.js
  webapp/src/containers/Loans/LoanEditTask.js
  webapp/src/containers/Loans/LoanEmiViewPage.js
  webapp/src/containers/Loans/Loans.js
  webapp/src/containers/Loans/config.js
Labels: needs review

#189 Added Dashboard view more details of Loan and Activities table for CSP
  webapp/src/containers/Dashboard/DashboardViewMoreDetails.js
Labels: needs review

#191 Dashboards for Sesta admin and FPO admin
  webapp/src/Routes.js
  webapp/src/components/Datatable/Datatable.js
  webapp/src/containers/Activitytypes/ActivitytypePage.js
  webapp/src/containers/Dashboard/Dashboard.js
  webapp/src/containers/Dashboard/DashboardFPO.js
  webapp/src/containers/Dashboard/DashboardFPOViewMoreDetails.js
  webapp/src/containers/Dashboard/DashboardSestaAdmin.js
Labels: needs review

#192 Added dropdown for notation
  backend/strapi/extensions/crm-plugin/models/activity.settings.json
  backend/strapi/extensions/crm-plugin/models/activitytype.settings.json
  backend/strapi/extensions/crm-plugin/models/contact.settings.json
  webapp/src/constants/Constants.js
  webapp/src/containers/Activitytypes/ActivitytypePage.js
Labels: needs review

#193 Updated Dashboard EMI Due table, Added search filter, fixed loan approval, add rupee symbol
  webapp/src/Routes.js
  webapp/src/components/UI/Piechart/Piechart.js
  webapp/src/containers/Activities/Activity.js
  webapp/src/containers/Dashboard/Dashboard.js
  webapp/src/containers/Dashboard/DashboardCSP.js
  webapp/src/containers/Dashboard/DashboardViewMoreDetails.js
  webapp/src/containers/Dashboard/DashboardViewMoreDetailsCSP.js
  webapp/src/containers/Loans/LoanApprovalPage.js
  webapp/src/containers/Loans/LoanEditEmiPage.js
  webapp/src/containers/Loans/LoanEmiPage.js
  webapp/src/containers/Loans/LoanEmiViewPage.js
  webapp/src/containers/Loans/Loans.js
Labels: needs review

#194 Issue fixes related to FPO dashboard, activity type, loan approval page
  webapp/src/containers/Activities/Activity.js
  webapp/src/containers/Activities/ActivityPage.js
  webapp/src/containers/Activitytypes/ActivitytypePage.js
  webapp/src/containers/Dashboard/DashboardFPO.js
  webapp/src/containers/Dashboard/DashboardFPOViewMoreDetails.js
  webapp/src/containers/Dashboard/DashboardSestaAdmin.js
  webapp/src/containers/Loans/LoanApprovalPage.js
  webapp/src/containers/Loans/Loans.js
Labels: bug

#195 Fixes on dashboard and Loans page
  webapp/src/containers/Dashboard/DashboardCSP.js
  webapp/src/containers/Dashboard/DashboardViewMoreDetailsCSP.js
  webapp/src/containers/Loans/LoanEditTask.js
  webapp/src/containers/Loans/LoanEmiPage.js
  webapp/src/containers/Loans/LoanEmiViewPage.js
  webapp/src/containers/Loans/LoanUpdateTaskPage.js
  webapp/src/containers/Loans/Loans.js
  webapp/src/containers/Loans/LoansPage.js
Labels: needs review

#196 Added reports menu, pages for CSP summary report and CSP activity report
  backend/strapi/hooks/autoload/data.js
  webapp/src/Routes.js
  webapp/src/components/Navigation/NavigationItems/NavigationItems.js
  webapp/src/containers/Dashboard/DashboardFPO.js
  webapp/src/containers/Dashboard/DashboardSestaAdmin.js
  webapp/src/containers/Dashboard/DashboardViewMoreDetailsCSP.js
  webapp/src/containers/Loans/LoansPage.js
  webapp/src/containers/Reports/CSPActivityReport.js
  webapp/src/containers/Reports/CSPSummaryReport.js
  webapp/src/containers/Reports/Reports.js
  webapp/src/containers/Reports/config.js
Labels: feature, needs review

#223 Added CSP Activity report, Download CSV for Recent activities and csp…
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/Datatable/Datatable.js
  webapp/src/containers/Activities/ActivityPage.js
  webapp/src/containers/Dashboard/DashboardCSP.js
  webapp/src/containers/Dashboard/DashboardViewMoreDetailsCSP.js
  webapp/src/containers/Loans/LoanEditEmiPage.js
  webapp/src/containers/Reports/CSPActivityReport.js
Labels: needs review

#225 CSP Summary Report done
  webapp/src/containers/Reports/CSPActivityReport.js
  webapp/src/containers/Reports/CSPSummaryReport.js
  webapp/src/containers/Reports/Reports.js
Labels: needs review

#226 Resolved issue 215: Fixed state, district, village dependent fields on page Member, SHG, Vi…
  webapp/src/containers/Members/MembersPage.js
  webapp/src/containers/Shgs/ShgPage.js
  webapp/src/containers/Villages/VillagePage.js
Labels: needs review

#228 Fixed CSP activity report member name
  webapp/src/containers/Reports/CSPActivityReport.js
Labels: needs review
